import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Download, FileSpreadsheet } from "lucide-react";
import { api } from "../../lib/api";
import { Empty, ErrorBox, Money, Page, Spinner } from "../../components/ui";
import { formatTransactionDate } from "../transactions/date";

type ReportTransaction = { id: string; date: string; description: string; type: "INCOME" | "EXPENSE" | "TRANSFER"; amount: string; account: string; category: string };
type Report = { currency: string; income: string; expenses: string; netCashFlow: string; totalBalance: string; from: string; to: string; accounts: Array<{ name: string; balance: string; currency: string }>; categories: Array<{ name: string; amount: string; color: string }>; transactions: ReportTransaction[]; trend: Array<{ label: string; income: string; expense: string }>; biggestExpenses: Array<{ id: string; date: string; description: string; account: string; amount: string }> };

export function Reports() {
  const [period, setPeriod] = useState("month");
  const [exporting, setExporting] = useState<"pdf" | "excel" | null>(null);
  const [exportError, setExportError] = useState<unknown>();
  const [exported, setExported] = useState(false);
  const q = useQuery({ queryKey: ["report", period], queryFn: () => api.get<Report>(`/reports/summary?period=${period}`) });
  if (q.isLoading) return <Spinner/>;
  if (q.error) return <Page title="Reports"><ErrorBox error={q.error}/><button className="btn-secondary mt-3" onClick={() => void q.refetch()}>Try again</button></Page>;

  async function download(type: "pdf" | "excel") {
    setExporting(type); setExportError(undefined); setExported(false);
    try { await api.download(`/reports/export/${type}?period=${period}`); setExported(true); }
    catch (error) { setExportError(error); }
    finally { setExporting(null); }
  }

  const hasActivity = Boolean(q.data?.transactions.length);
  const hasExpenses = Boolean(q.data?.categories.length);
  return <Page title="Reports" description="Understand your cash flow and keep useful records." action={<label><span className="sr-only">Report period</span><select className="input !w-auto" value={period} onChange={event => setPeriod(event.target.value)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></label>}>
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Income", q.data?.income, "text-green-700"], ["Expenses", q.data?.expenses, "text-red-600"], ["Net flow", q.data?.netCashFlow, "text-pocket-700"], ["Balance", q.data?.totalBalance, "text-slate-900"]].map(([label, value, color]) => <div className="card min-w-0" key={label}><p className="text-xs font-medium text-slate-500">{label}</p><Money value={value ?? 0} currency={q.data?.currency} className={`mt-2 block break-words font-bold sm:text-lg ${color}`}/></div>)}</div>
    {hasActivity && q.data?.trend.length ? <section className="card mt-5"><h2 className="section-title">Cash-flow trend</h2><p className="mt-1 text-sm text-slate-500">Income and expenses by day in the selected period</p><div className="mt-5 h-64" aria-hidden="true"><ResponsiveContainer><BarChart data={q.data.trend}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3"/><XAxis dataKey="label" tick={{ fontSize: 10, fill: "#64748b" }}/><YAxis tick={{ fontSize: 11, fill: "#475569" }}/><Tooltip formatter={value => new Intl.NumberFormat("en-BD", { style: "currency", currency: q.data?.currency ?? "BDT" }).format(Number(value))}/><Bar dataKey="income" fill="#15803d" radius={[5, 5, 0, 0]}/><Bar dataKey="expense" fill="#dc2626" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></div></section> : null}
    {hasExpenses ? <section className="card mt-5"><h2 className="section-title">Spending by category</h2><p className="mt-1 text-sm text-slate-500">Expense transactions only</p><div className="mt-5 h-64" aria-hidden="true"><ResponsiveContainer><BarChart data={q.data?.categories} layout="vertical" margin={{ left: 2, right: 12 }}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tick={{ fontSize: 11, fill: "#64748b" }}/><YAxis type="category" dataKey="name" width={76} tick={{ fontSize: 11, fill: "#475569" }}/><Tooltip formatter={value => new Intl.NumberFormat("en-BD", { style: "currency", currency: q.data?.currency ?? "BDT" }).format(Number(value))}/><Bar dataKey="amount" fill="#0d9488" radius={[0, 7, 7, 0]}/></BarChart></ResponsiveContainer></div><div className="border-t border-slate-100 pt-4" aria-label="Spending by category values">{q.data?.categories.map(category => <div className="flex items-center justify-between gap-3 py-1.5 text-sm" key={category.name}><span className="text-slate-600">{category.name}</span><Money value={category.amount} currency={q.data?.currency} className="font-semibold"/></div>)}</div></section> : <div className="mt-5"><Empty title={hasActivity ? "No expenses in this period" : "No report data"} text={hasActivity ? "Income and internal transfers do not count as spending." : "Record income or expenses to see a report for this period."}/></div>}
    {q.data?.accounts.length ? <section className="mt-5"><h2 className="section-title">Account balances</h2><p className="mb-3 mt-1 text-sm text-slate-500">Current balances across active accounts</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{q.data.accounts.map(account => <div className="card" key={account.name}><p className="truncate font-semibold">{account.name}</p><Money value={account.balance} currency={account.currency} className="mt-3 block text-lg font-bold"/></div>)}</div></section> : null}
    {q.data?.biggestExpenses.length ? <section className="card mt-5"><h2 className="section-title">Biggest expenses</h2><p className="mt-1 text-sm text-slate-500">Largest expenses in this period</p><div className="mt-3 divide-y divide-slate-100">{q.data.biggestExpenses.map(expense => <div className="flex items-center justify-between gap-3 py-3" key={expense.id}><div className="min-w-0"><p className="truncate font-semibold">{expense.description}</p><p className="mt-1 truncate text-xs text-slate-500">{formatTransactionDate(expense.date)} · {expense.account}</p></div><Money value={expense.amount} currency={q.data?.currency} className="shrink-0 font-bold text-red-600"/></div>)}</div></section> : null}
    {hasActivity ? <section className="card mt-5"><h2 className="section-title">Report activity</h2><p className="mt-1 text-sm text-slate-500">Transfers are shown for context but excluded from cash-flow totals.</p><div className="mt-3 divide-y divide-slate-100">{q.data?.transactions.slice(0, 20).map(transaction => <div className="flex items-center justify-between gap-3 py-3" key={transaction.id}><div className="min-w-0"><p className="truncate font-semibold">{transaction.description}</p><p className="mt-1 truncate text-xs text-slate-500">{formatTransactionDate(transaction.date)} · {transaction.account} · {transaction.type === "TRANSFER" ? "Transfer" : transaction.type === "INCOME" ? "Income" : "Expense"}</p></div><Money value={transaction.amount} currency={q.data?.currency} className={`shrink-0 font-bold ${transaction.type === "EXPENSE" ? "text-red-600" : transaction.type === "INCOME" ? "text-green-700" : "text-slate-600"}`}/></div>)}</div></section> : null}
    <section className="mt-5"><h2 className="section-title">Export records</h2><p className="mt-1 text-sm text-slate-500">Save a copy for your records or bookkeeping.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><button className="btn-primary" disabled={Boolean(exporting)} onClick={() => void download("pdf")}><Download size={18}/>{exporting === "pdf" ? "Preparing PDF..." : "Download PDF"}</button><button className="btn-secondary" disabled={Boolean(exporting)} onClick={() => void download("excel")}><FileSpreadsheet size={18}/>{exporting === "excel" ? "Preparing Excel..." : "Download Excel"}</button></div>{Boolean(exportError) && <div className="mt-3"><ErrorBox error={exportError}/></div>}{exported && <p role="status" className="mt-3 rounded-xl bg-green-50 p-3 text-sm font-medium text-green-800">Your report download is ready.</p>}</section>
    <p className="mt-6 rounded-xl bg-slate-100 p-3 text-xs leading-5 text-slate-600">Reports are bookkeeping records. AccPocket does not move real money.</p>
  </Page>;
}
