import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileSpreadsheet } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../../lib/api";
import { Empty, ErrorBox, Money, Page, Spinner } from "../../components/ui";
import { formatTransactionDate } from "../transactions/date";
import { reportLimitMessage, type ReportDetailLimit } from "./model";

type ReportTransaction = { id: string; date: string; title: string; description: string; type: "INCOME" | "EXPENSE" | "TRANSFER"; amount: string; account: string; category: string };
type Report = { currency: string; income: string; expenses: string; netCashFlow: string; totalBalance: string; from: string; to: string; accounts: Array<{ name: string; balance: string; currency: string }>; categories: Array<{ name: string; amount: string; color: string }>; transactions: ReportTransaction[]; detail: ReportDetailLimit; trend: Array<{ label: string; income: string; expense: string }>; biggestExpenses: Array<{ id: string; date: string; title: string; description: string; account: string; amount: string }> };
type SortKey = "date" | "title" | "amount";

export function Reports() {
  const [period, setPeriod] = useState("month"), [search, setSearch] = useState(""), [type, setType] = useState("ALL"), [title, setTitle] = useState("ALL"), [sort, setSort] = useState<SortKey>("date"), [ascending, setAscending] = useState(false);
  const [exporting, setExporting] = useState<"pdf" | "excel" | null>(null), [exportError, setExportError] = useState<unknown>(), [exported, setExported] = useState(false);
  const q = useQuery({ queryKey: ["report", period], queryFn: ({ signal }) => api.get<Report>(`/reports/summary?period=${period}`, { signal }) });
  const titles = useMemo(() => [...new Set(q.data?.transactions.map(row => row.title) ?? [])].sort((a, b) => a.localeCompare(b)), [q.data]);
  const rows = useMemo(() => {
    const needle = search.trim().toLocaleLowerCase();
    return (q.data?.transactions ?? []).filter(row => (type === "ALL" || row.type === type) && (title === "ALL" || row.title === title) && (!needle || [row.title, row.description, row.category, row.account, row.type].some(value => value.toLocaleLowerCase().includes(needle)))).sort((left, right) => {
      const compared = sort === "amount" ? Number(left.amount) - Number(right.amount) : sort === "title" ? left.title.localeCompare(right.title) : left.date.localeCompare(right.date);
      return ascending ? compared : -compared;
    });
  }, [q.data, search, type, title, sort, ascending]);
  if (q.isLoading) return <Spinner/>;
  if (q.error) return <Page title="Reports"><ErrorBox error={q.error}/><button className="btn-secondary mt-3" onClick={() => void q.refetch()}>Try again</button></Page>;
  async function download(format: "pdf" | "excel") { setExporting(format); setExportError(undefined); setExported(false); try { await api.download(`/reports/export/${format}?period=${period}`); setExported(true); } catch (error) { setExportError(error); } finally { setExporting(null); } }
  const hasActivity = Boolean(q.data?.transactions.length), hasExpenses = Boolean(q.data?.categories.length);
  return <Page title="Reports" description="Understand your cash flow and keep useful records." action={<label><span className="sr-only">Report period</span><select className="input !w-auto" value={period} onChange={event => setPeriod(event.target.value)}><option value="day">Daily</option><option value="week">Weekly</option><option value="month">Monthly</option></select></label>}>
    {q.data?.detail && reportLimitMessage(q.data.detail) && <p role="status" className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{reportLimitMessage(q.data.detail)}</p>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Total balance", q.data?.totalBalance, "text-slate-900"], ["Income", q.data?.income, "text-green-700"], ["Expenses", q.data?.expenses, "text-red-600"], ["Net cash flow", q.data?.netCashFlow, "text-pocket-700"]].map(([label, value, color]) => <div className="card" key={label}><p className="eyebrow">{label}</p><Money value={value ?? "0"} currency={q.data?.currency} className={`mt-3 block text-xl font-bold ${color}`}/></div>)}</div>
    {q.data?.accounts.length ? <section className="mt-5"><h2 className="section-title">Wallet balances</h2><p className="mb-3 mt-1 text-sm text-slate-500">Current balances across active wallets</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{q.data.accounts.map(account => <div className="card" key={account.name}><p className="truncate font-semibold">{account.name}</p><Money value={account.balance} currency={account.currency} className="mt-3 block text-lg font-bold"/></div>)}</div></section> : null}
    {hasActivity && q.data?.trend.length ? <section className="card mt-5"><h2 className="section-title">Cash-flow trend</h2><p className="mt-1 text-sm text-slate-500">Income and expenses by day in the selected period</p><div className="mt-5 h-64" aria-hidden="true"><ResponsiveContainer><BarChart data={q.data.trend}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3"/><XAxis dataKey="label" tick={{ fontSize: 10, fill: "#64748b" }}/><YAxis tick={{ fontSize: 11, fill: "#475569" }}/><Tooltip/><Bar dataKey="income" fill="#15803d" radius={[5, 5, 0, 0]}/><Bar dataKey="expense" fill="#dc2626" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></div></section> : null}
    {hasExpenses ? <section className="card mt-5"><h2 className="section-title">Spending by category</h2><div className="mt-5 h-64" aria-hidden="true"><ResponsiveContainer><BarChart data={q.data?.categories} layout="vertical"><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="name" width={76}/><Tooltip/><Bar dataKey="amount" fill="#0d9488" radius={[0, 7, 7, 0]}/></BarChart></ResponsiveContainer></div></section> : null}
    {q.data?.biggestExpenses.length ? <section className="card mt-5"><h2 className="section-title">Biggest expenses</h2><div className="mt-3 divide-y divide-slate-100">{q.data.biggestExpenses.map(expense => <div className="flex items-center justify-between gap-3 py-3" key={expense.id}><div className="min-w-0"><p className="truncate font-semibold">{expense.title}</p><p className="truncate text-xs text-slate-500">{expense.description || "No description"} · {formatTransactionDate(expense.date)} · {expense.account}</p></div><Money value={expense.amount} currency={q.data?.currency} className="shrink-0 font-bold text-red-600"/></div>)}</div></section> : null}
    {hasActivity ? <section className="card mt-5"><h2 className="section-title">Transaction report</h2><p className="mt-1 text-sm text-slate-500">Search, filter, and sort every field, including Transaction Title.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><input className="input lg:col-span-2" type="search" placeholder="Search title, description, category…" value={search} onChange={event => setSearch(event.target.value)}/><select className="input" aria-label="Filter by transaction type" value={type} onChange={event => setType(event.target.value)}><option value="ALL">All types</option><option value="INCOME">Income</option><option value="EXPENSE">Expense</option><option value="TRANSFER">Transfer</option></select><select className="input" aria-label="Filter by Transaction Title" value={title} onChange={event => setTitle(event.target.value)}><option value="ALL">All titles</option>{titles.map(item => <option key={item}>{item}</option>)}</select><div className="flex gap-2"><select className="input" aria-label="Sort transactions" value={sort} onChange={event => setSort(event.target.value as SortKey)}><option value="date">Date</option><option value="title">Title</option><option value="amount">Amount</option></select><button className="btn-secondary !px-3" aria-label={ascending ? "Sort descending" : "Sort ascending"} onClick={() => setAscending(value => !value)}>{ascending ? "↑" : "↓"}</button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Date</th><th className="p-3">Transaction Title</th><th className="p-3">Description</th><th className="p-3">Type</th><th className="p-3">Category</th><th className="p-3">Wallet</th><th className="p-3 text-right">Amount</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.id}><td className="whitespace-nowrap p-3">{formatTransactionDate(row.date)}</td><td className="p-3 font-semibold">{row.title}</td><td className="p-3 text-slate-600">{row.description || "—"}</td><td className="p-3">{row.type}</td><td className="p-3">{row.category}</td><td className="p-3">{row.account}</td><td className="p-3 text-right"><Money value={row.amount} currency={q.data?.currency}/></td></tr>)}</tbody></table>{!rows.length && <Empty title="No matching transactions" text="Adjust the search or filters to see report activity."/>}</div></section> : <div className="mt-5"><Empty title="No report data" text="Record income or expenses to see a report for this period."/></div>}
    <section className="mt-5"><h2 className="section-title">Export records</h2><p className="mt-1 text-sm text-slate-500">PDF and Excel exports include Transaction Title.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><button className="btn-primary" disabled={Boolean(exporting)} onClick={() => void download("pdf")}><Download size={18}/>{exporting === "pdf" ? "Preparing PDF…" : "Download PDF"}</button><button className="btn-secondary" disabled={Boolean(exporting)} onClick={() => void download("excel")}><FileSpreadsheet size={18}/>{exporting === "excel" ? "Preparing Excel…" : "Download Excel"}</button></div>{Boolean(exportError) && <div className="mt-3"><ErrorBox error={exportError}/></div>}{exported && <p role="status" className="mt-3 rounded-xl bg-green-50 p-3 text-sm font-medium text-green-800">Your report download is ready.</p>}</section>
  </Page>;
}
