import crypto from "node:crypto";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import cookieParser from "cookie-parser";
import { rateLimit } from "express-rate-limit";
import { env } from "./config/env.js";
import { prisma } from "./config/prisma.js";
import { authRouter } from "./modules/auth/routes.js";
import { passcodeRouter } from "./modules/passcode/routes.js";
import { financeRouter } from "./modules/finance/routes.js";
import { dashboardRouter } from "./modules/dashboard/routes.js";
import { reportsRouter } from "./modules/reports/routes.js";
import { meRouter, settingsRouter } from "./modules/settings/routes.js";
import { errorHandler, notFound } from "./utils/errors.js";
import { responseCompression } from "./middleware/compression.js";
import { performanceTelemetry } from "./middleware/performance.js";

export const app = express();
app.set("trust proxy", 1);
app.use((req, res, next) => { req.id = String(req.header("x-request-id") ?? crypto.randomUUID()); res.setHeader("x-request-id", req.id); next(); });
app.use(helmet());
app.use(responseCompression);
app.use(cors({ origin: env.WEB_ORIGIN, credentials: true, methods: ["GET", "POST", "PATCH", "DELETE"] }));
app.use(express.json({ limit: "256kb" })); app.use(cookieParser());
app.use("/api/v1/auth", rateLimit({ windowMs: 15 * 60000, limit: 100, standardHeaders: "draft-7", legacyHeaders: false }), authRouter);
app.get("/health", (_req, res) => res.json({ status: "ok" }));
app.get("/ready", performanceTelemetry("readiness"), async (_req, res) => { try { await prisma.$queryRaw`SELECT 1`; res.json({ status: "ready" }); } catch { res.status(503).json({ status: "unavailable" }); } });
app.use("/api/v1/passcode", rateLimit({ windowMs: 15 * 60000, limit: 30, standardHeaders: "draft-7", legacyHeaders: false }), passcodeRouter);
app.use("/api/v1/dashboard", dashboardRouter);
app.use("/api/v1/reports", reportsRouter);
app.use("/api/v1/me", meRouter);
app.use("/api/v1/settings", settingsRouter);
app.use("/api/v1", financeRouter);
app.use(notFound); app.use(errorHandler);
