import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useSearchParams } from "react-router-dom";
import type { AccountDto, TransactionDto } from "@accpocket/shared";
import { ArrowDownLeft, ArrowRightLeft, ArrowUpRight, Plus } from "lucide-react";
import { api } from "../../lib/api";
import { activeAccounts, canAddEntry, canTransfer } from "../../lib/accountRequirements";
import { useAuth } from "../../store/auth";
import { Empty, ErrorBox, Modal, Money, Page, Spinner } from "../../components/ui";
import { formatTransactionDate, localDateInputValue } from "./date";
import { TRANSACTION_PAGE_SIZE, transactionTotalPages } from "./pagination";

type Category = { id: string; name: string; type: "INCOME" | "EXPENSE" };
export type TransactionTitle = { id: string; categoryId: string; name: string; type: "INCOME" | "EXPENSE"; isActive: boolean; category: Category; _count: { transactions: number } };
type Result = { items: TransactionDto[]; total: number };
type Mode = "INCOME" | "EXPENSE" | "TRANSFER";

export function filterTitles(titles: TransactionTitle[] | undefined, categoryId: string) { return titles?.filter(title => title.categoryId === categoryId && title.isActive) ?? []; }
export function transactionDisplayTitle(transaction: Pick<TransactionDto, "description" | "transactionTitle">) { return transaction.transactionTitle?.name ?? transaction.description; }
export function deleteTitleConfirmation(title: Pick<TransactionTitle, "name" | "_count">) {
  return title._count.transactions > 0
    ? `Delete “${title.name}”? This title is used by existing transactions, so it will be archived instead. Historical transactions will keep displaying it.`
    : `Permanently delete “${title.name}”? This transaction title has not been used and cannot be recovered.`;
}

export function Transactions() {
  const [params, setParams] = useSearchParams();
  const [page, setPage] = useState(1), [mode, setMode] = useState<Mode | null>(null);
  const [accountNotice, setAccountNotice] = useState<string | null>(null);
  const [sourceAccountId, setSourceAccountId] = useState(""), [destinationAccountId, setDestinationAccountId] = useState("");
  const [categoryId, setCategoryId] = useState(""), [transactionTitleId, setTransactionTitleId] = useState("");
  const [addTitleOpen, setAddTitleOpen] = useState(false), [manageTitlesOpen, setManageTitlesOpen] = useState(false), [titleName, setTitleName] = useState("");
  const { user } = useAuth(); const queryClient = useQueryClient();
  const transactions = useQuery({ queryKey: ["transactions", page], queryFn: ({ signal }) => api.get<Result>(`/transactions?page=${page}&limit=${TRANSACTION_PAGE_SIZE}`, { signal }), placeholderData: previous => previous });
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: ({ signal }) => api.get<AccountDto[]>("/accounts", { signal }) });
  const categories = useQuery({ queryKey: ["categories"], queryFn: ({ signal }) => api.get<Category[]>("/categories", { signal }) });
  const titles = useQuery({ queryKey: ["transaction-titles", categoryId], queryFn: ({ signal }) => api.get<TransactionTitle[]>(`/transaction-titles?categoryId=${encodeURIComponent(categoryId)}`, { signal }), enabled: Boolean(categoryId) });
  const managedTitles = useQuery({ queryKey: ["transaction-titles", "manage"], queryFn: ({ signal }) => api.get<TransactionTitle[]>("/transaction-titles?includeArchived=true", { signal }), enabled: manageTitlesOpen });
  const availableAccounts = activeAccounts(accounts.data);
  const refresh = () => void queryClient.invalidateQueries({ queryKey: ["transaction-titles"] });
  const add = useMutation({ mutationFn: (body: unknown) => mode === "TRANSFER" ? api.post("/transfers", body) : api.post("/transactions", body), onSuccess: () => { setPage(1); for (const key of ["transactions", "accounts", "dashboard", "budgets", "goals", "report"]) void queryClient.invalidateQueries({ queryKey: [key] }); setMode(null); } });
  const createTitle = useMutation({ mutationFn: (body: { name: string; categoryId: string; type: "INCOME" | "EXPENSE" }) => api.post<TransactionTitle>("/transaction-titles", body), onSuccess: row => { refresh(); setTransactionTitleId(row.id); setAddTitleOpen(false); setTitleName(""); } });
  const changeTitle = useMutation({ mutationFn: ({ id, body }: { id: string; body: object }) => api.patch(`/transaction-titles/${id}`, body), onSuccess: refresh });
  const removeTitle = useMutation({ mutationFn: (id: string) => api.delete(`/transaction-titles/${id}`), onSuccess: () => { refresh(); setTransactionTitleId(""); } });

  useEffect(() => { if (params.get("add") !== "expense" || !accounts.isSuccess) return; if (canAddEntry(accounts.data)) { add.reset(); setMode("EXPENSE"); } else setAccountNotice("Create a wallet first before adding a transaction."); setParams({}, { replace: true }); }, [accounts.data, accounts.isSuccess, params, setParams]);
  if (transactions.isLoading) return <Spinner/>;
  function openEntry() { if (!accounts.isSuccess) return; if (!canAddEntry(accounts.data)) return setAccountNotice("Create a wallet first before adding a transaction."); setAccountNotice(null); add.reset(); setMode("EXPENSE"); }
  function openTransfer() { if (!accounts.isSuccess) return; if (!canTransfer(accounts.data)) return setAccountNotice(availableAccounts.length ? "Create another wallet first before making a transfer." : "Create a wallet first before making a transfer."); setSourceAccountId(""); setDestinationAccountId(""); add.reset(); setMode("TRANSFER"); }
  function closeModal() { add.reset(); setMode(null); setCategoryId(""); setTransactionTitleId(""); setAddTitleOpen(false); setManageTitlesOpen(false); }
  function changeMode(next: "INCOME" | "EXPENSE") { add.reset(); setMode(next); setCategoryId(""); setTransactionTitleId(""); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); add.mutate(mode === "TRANSFER" ? { sourceAccountId: data.accountId, destinationAccountId: data.destinationAccountId, amount: data.amount, description: data.description, notes: data.notes || undefined, date: data.date } : { accountId: data.accountId, categoryId: data.categoryId || undefined, transactionTitleId: data.transactionTitleId || undefined, type: mode, amount: data.amount, description: data.description, notes: data.notes || undefined, date: data.date }); }
  const totalPages = transactionTotalPages(transactions.data?.total ?? 0);

  return <Page title="Transactions" description="Income, expenses, and transfers in date order." action={<><button className="btn-secondary" disabled={accounts.isLoading || accounts.isError} onClick={openTransfer}><ArrowRightLeft size={18}/>Transfer</button><button className="btn-primary" disabled={accounts.isLoading || accounts.isError} onClick={openEntry}><Plus size={18}/>Add</button></>}>
    {accounts.error && <ErrorBox error={accounts.error}/>} {accountNotice && <div role="status" className="mb-5 rounded-xl bg-pocket-50 p-4 text-sm">{accountNotice} <Link className="btn-tonal ml-2" to="/accounts">Go to wallet</Link></div>} {transactions.error && <ErrorBox error={transactions.error}/>}
    {!transactions.error && <div className="space-y-2">{transactions.data?.items.map(transaction => { const expense = transaction.type === "EXPENSE", income = transaction.type === "INCOME"; const Icon = expense ? ArrowUpRight : income ? ArrowDownLeft : ArrowRightLeft; return <article className="card flex items-center justify-between gap-3" key={transaction.id}><div className="flex min-w-0 items-center gap-3"><Icon size={20}/><div className="min-w-0"><p className="truncate font-semibold">{transactionDisplayTitle(transaction)}</p>{transaction.transactionTitle && <p className="truncate text-xs">{transaction.description}</p>}<p className="text-xs text-slate-500">{formatTransactionDate(transaction.date)} · {expense ? "Expense" : income ? "Income" : "Transfer"}</p></div></div><Money value={transaction.amount} currency={user?.defaultCurrency} className="font-bold"/></article>; })}</div>}
    {!transactions.error && totalPages > 1 && <nav className="mt-5 flex items-center justify-between"><button className="btn-secondary" disabled={page === 1} onClick={() => setPage(value => value - 1)}>Previous</button><span>Page {page} of {totalPages}</span><button className="btn-secondary" disabled={page >= totalPages} onClick={() => setPage(value => value + 1)}>Next</button></nav>}
    {!transactions.error && !transactions.data?.items.length && <Empty title="No transactions" text="Record income, expenses, or internal transfers."/>}
    {mode && <Modal title={mode === "TRANSFER" ? "Internal transfer" : `Add ${mode.toLowerCase()}`} close={closeModal}><form className="space-y-5" onSubmit={submit}>
      {mode !== "TRANSFER" && <div className="grid grid-cols-2 gap-2"><button type="button" className={mode === "INCOME" ? "btn-primary" : "btn-secondary"} onClick={() => changeMode("INCOME")}><ArrowDownLeft size={18}/>Income</button><button type="button" className={mode === "EXPENSE" ? "btn-primary" : "btn-secondary"} onClick={() => changeMode("EXPENSE")}><ArrowUpRight size={18}/>Expense</button></div>}
      <label className="block"><span className="label">{mode === "TRANSFER" ? "From wallet" : "Wallet"}</span><select className="input" name="accountId" required value={mode === "TRANSFER" ? sourceAccountId : undefined} onChange={mode === "TRANSFER" ? event => { setSourceAccountId(event.target.value); if (event.target.value === destinationAccountId) setDestinationAccountId(""); } : undefined}><option value="">Choose wallet</option>{availableAccounts.map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label>
      {mode === "TRANSFER" && <label className="block"><span className="label">To wallet</span><select className="input" name="destinationAccountId" required value={destinationAccountId} onChange={event => setDestinationAccountId(event.target.value)}><option value="">Choose wallet</option>{availableAccounts.filter(account => account.id !== sourceAccountId).map(account => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label>}
      {mode !== "TRANSFER" && <><label className="block"><span className="label">Category (optional)</span><select className="input" name="categoryId" value={categoryId} onChange={event => { setCategoryId(event.target.value); setTransactionTitleId(""); }}><option value="">Uncategorized</option>{categories.data?.filter(category => category.type === mode).map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div><label className="block"><span className="label">Transaction Title (optional)</span><select className="input" name="transactionTitleId" value={transactionTitleId} onChange={event => setTransactionTitleId(event.target.value)} disabled={!categoryId}><option value="">{categoryId ? "No transaction title" : "Choose a category first"}</option>{filterTitles(titles.data, categoryId).map(title => <option key={title.id} value={title.id}>{title.name}</option>)}</select></label><div className="mt-2 flex justify-end gap-2"><button type="button" className="btn-tonal" disabled={!categoryId} onClick={() => { createTitle.reset(); setTitleName(""); setAddTitleOpen(true); }}>+ Add title</button><button type="button" className="btn-secondary" onClick={() => setManageTitlesOpen(true)}>Manage titles</button></div></div></>}
      <label className="block"><span className="label">Amount</span><input className="input-amount" name="amount" type="number" min="0.0001" step="0.0001" required/></label><label className="block"><span className="label">Date</span><input className="input" name="date" type="date" defaultValue={localDateInputValue()} required/></label><label className="block"><span className="label">Description</span><input className="input" name="description" maxLength={120} defaultValue={mode === "TRANSFER" ? "Internal transfer" : ""} required/></label><label className="block"><span className="label">Notes (optional)</span><textarea className="input min-h-24" name="notes" maxLength={500}/></label>{add.error && <ErrorBox error={add.error}/>}<button className="btn-primary w-full" disabled={add.isPending}>{add.isPending ? "Saving…" : "Save entry"}</button>
    </form></Modal>}
    {addTitleOpen && (mode === "INCOME" || mode === "EXPENSE") && <Modal title="Add transaction title" close={() => setAddTitleOpen(false)}><form className="space-y-5" onSubmit={event => { event.preventDefault(); if (mode !== "INCOME" && mode !== "EXPENSE") return; createTitle.mutate({ name: titleName, categoryId, type: mode }); }}><label className="block"><span className="label">Transaction Title name</span><input className="input" value={titleName} onChange={event => setTitleName(event.target.value)} maxLength={80} required autoFocus/></label><p className="text-sm text-slate-600">{mode === "INCOME" ? "Income" : "Expense"} · {categories.data?.find(category => category.id === categoryId)?.name}</p>{createTitle.error && <ErrorBox error={createTitle.error}/>}<button className="btn-primary w-full" disabled={createTitle.isPending}>{createTitle.isPending ? "Saving…" : "Add title"}</button></form></Modal>}
    {manageTitlesOpen && <Modal title="Manage transaction titles" close={() => setManageTitlesOpen(false)}><div className="space-y-5">{managedTitles.data?.map(title => <article className="rounded-xl border p-3" key={title.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{title.name}</strong><p className="text-xs text-slate-500">{title.type === "INCOME" ? "Income" : "Expense"} · {title.category.name} · {title.isActive ? "Active" : "Archived"}</p></div><div className="flex flex-wrap gap-2">{title.isActive ? <><button className="btn-secondary" onClick={() => { const name = window.prompt("Transaction title name", title.name)?.trim(); if (name) changeTitle.mutate({ id: title.id, body: { name } }); }}>Edit</button><button className="btn-secondary" onClick={() => { if (window.confirm(deleteTitleConfirmation(title))) removeTitle.mutate(title.id); }}>Delete</button>{title._count.transactions > 0 && <button className="btn-secondary" onClick={() => { if (window.confirm(`Archive “${title.name}”? It will be hidden from new transactions but remain visible in historical transactions.`)) changeTitle.mutate({ id: title.id, body: { isActive: false } }); }}>Archive</button>}</> : <button className="btn-tonal" onClick={() => changeTitle.mutate({ id: title.id, body: { isActive: true } })}>Reactivate</button>}</div></div></article>)}{managedTitles.error && <ErrorBox error={managedTitles.error}/>} {!managedTitles.isLoading && !managedTitles.data?.length && <p className="text-sm text-slate-500">No transaction titles yet.</p>}</div></Modal>}
  </Page>;
}
